version: '3.3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: carangobom
    volumes:
    - my-db:/var/lib/postgresql/data

  api:
    image: carangobom-api
    environment:
        DB_HOST: database
    ports:
        - "8080:8080"

# Names our volume
volumes:
  my-db: